const uploadFileToFTP = require('../utils/ftpUpload');
// ...existing code...

async function addPlant(req, res) {
    // ...existing code...
    const { filePath, fileName } = req.body;
    await uploadFileToFTP(filePath, fileName);
    // ...existing code...
    res.render('plantDetails', { plant });
}

// ...existing code...
