name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Change to demo directory
        run: cd demo

      - name: Install dependencies
        run: npm install
        working-directory: demo

      - name: Run tests
        run: npm test
        working-directory: demo